local M = {}

M.icons = {
--  Class       = "  ",
--  Color		= "  ",
--  Constant	= "  ",
--  Constructor = "  ",
--  Enum		= " 了",
--  EnumMember  = "  ",
--  Field		= "  ",
--  File		= "  ",
--  Folder		= "  ",
--  Function	= "  ",
--  Interface	= " ﰮ ",
--  Keyword		= "  ",
--  Method		= " ƒ ",
--  Module		= "  ",
--  Property	= "  ",
--  Snippet		= "  ",
--  Struct		= "  ",
--  Text		= "  ",
--  Unit		= "  ",
--  Value		= "  ",
--  Variable	= "  ",

    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "",
    Variable = "",
    Class = "ﴯ",
    Interface = "",
    Module = "",
    Property = "ﰠ",
    Unit = "塞",
    Value = "",
    Enum = "了",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "פּ",
    Event = "",
    Operator = "",
    TypeParameter = "",
}

return M
